"""add status field in task

Revision ID: 5708d25ae57d
Revises: d52ec80a037e
Create Date: 2026-02-28 20:21:26.904512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5708d25ae57d'
down_revision: Union[str, Sequence[str], None] = 'd52ec80a037e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('tasks', sa.Column('status_id', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'tasks', 'statuses', ['status_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=320),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tasks', 'status_id')
    op.drop_table('statuses')
    # ### end Alembic commands ###
